### ISSUE TITLE
systemd cores on GCP

### ISSUE THREAD

**Issue by marwinski** [gardenlinux/gardenlinux#17]
We experience very slow cluster startups on GCP. The reason for this is that the extracting of docker layers is very slow. The root cause appears to be a systemd core dump around the time the kubelet starts. This does not happen on AWS wit a very similar software setup.

systemd restarts after the crash but it appears to be in an inconsistent state, e.g. commands like the following do fail:

```
root@shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-hg27v:/# systemctl
Failed to list units: Failed to activate service 'org.freedesktop.systemd1': timed out (service_start_timeout=25000ms)
```
systemd version is 
```
Apr 09 14:05:40 localhost systemd[1]: systemd 244.3-1 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid)
```
Issue appears to be easily reproducible (two nodes fail with similar symptoms).

Next steps:

- try with latest systemd version 245.4-2 available for Debian (unstatable)
- debug

These are the crash logs. A core dump file has bee secured but does not reveal additional information.

```
Apr 09 15:11:54 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz dbus-daemon[392]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.>
Apr 09 15:11:54 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz systemd[1]: Starting Hostname Service...
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz dbus-daemon[392]: [system] Successfully activated service 'org.freedesktop.hostname1'
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz systemd[1]: Started kubelet daemon.
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=kubelet comm="systemd" exe="/lib/systemd/systemd" hostname=? >
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz download-cloud-config.sh[2853]: Created symlink /etc/systemd/system/multi-user.target.wants/kubelet-monitor.service → /etc/systemd/system/kubelet-monitor.s>
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz systemd[1]: Reloading.
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz systemd[1]: /lib/systemd/system/logrotate.service:19: Unknown key name 'ProtectClock' in section 'Service', ignoring.
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz systemd[1]: /lib/systemd/system/docker.socket:6: ListenStream= references a path below legacy directory /var/run/, updating /var/run/docker.sock → /run/doc>
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=kubelet-monitor comm="systemd" exe="/lib/systemd/systemd" hos>
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz systemd[1]: Started Kubelet-monitor daemon.
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz health-monitor[2876]: Start kubernetes health monitoring for kubelet
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz health-monitor[2876]: Wait for 2 minutes for kubelet to be functional
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz systemd[1]: Reloading.
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz kernel: systemd[1]: segfault at 50 ip 0000562234075990 sp 00007ffe7fd0b060 error 4 in systemd[562234014000+b5000]
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz kernel: Code: a0 48 8b 75 98 c7 45 a4 00 00 00 00 48 8b 94 c7 90 05 00 00 48 89 45 80 48 89 f0 48 39 d6 74 17 66 2e 0f 1f 84 00 00 00 00 00 <48> 8b 40 50 8>
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz audit[2880]: ANOM_ABEND auid=4294967295 uid=0 gid=0 ses=4294967295 subj==unconfined pid=2880 comm="systemd" exe="/lib/systemd/systemd" sig=11 res=1
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz kubelet[2852]: I0409 15:11:55.550184    2852 flags.go:33] FLAG: --address="0.0.0.0"
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz kubelet[2852]: I0409 15:11:55.551265    2852 flags.go:33] FLAG: --allowed-unsafe-sysctls="[]"
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz kubelet[2852]: I0409 15:11:55.551413    2852 flags.go:33] FLAG: --alsolog
[...]
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz kubelet[2852]: I0409 15:11:55.557250    2852 flags.go:33] FLAG: --version="false"
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz kubelet[2852]: I0409 15:11:55.557284    2852 flags.go:33] FLAG: --vmodule=""
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz kubelet[2852]: I0409 15:11:55.557292    2852 flags.go:33] FLAG: --volume-plugin-dir="/var/lib/kubelet/volumeplugins"
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz kubelet[2852]: I0409 15:11:55.557299    2852 flags.go:33] FLAG: --volume-stats-agg-period="1m0s"
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz kubelet[2852]: I0409 15:11:55.557362    2852 feature_gate.go:216] feature gates: &{map[]}
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz kubelet[2852]: I0409 15:11:55.571891    2852 feature_gate.go:216] feature gates: &{map[]}
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz kubelet[2852]: I0409 15:11:55.571982    2852 feature_gate.go:216] feature gates: &{map[]}
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz systemd-coredump[2881]: Due to PID 1 having crashed coredump collection will now be turned off.
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz systemd[1]: Caught <SEGV>, dumped core as pid 2880.
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz systemd[1]: Freezing execution.
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz download-cloud-config.sh[2877]: Failed to reload daemon: Connection reset by peer
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz download-cloud-config.sh[2877]: The unit files have no installation config (WantedBy=, RequiredBy=, Also=,
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz download-cloud-config.sh[2877]: Alias= settings in the [Install] section, and DefaultInstance= for template
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz download-cloud-config.sh[2877]: units). This means they are not meant to be enabled using systemctl.
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz download-cloud-config.sh[2877]:
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz download-cloud-config.sh[2877]: Possible reasons for having this kind of units are:
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz download-cloud-config.sh[2877]: • A unit may be statically enabled by being symlinked from another unit's
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz download-cloud-config.sh[2877]:   .wants/ or .requires/ directory.
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz download-cloud-config.sh[2877]: • A unit's purpose may be to act as a helper for some other unit which has
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz download-cloud-config.sh[2877]:   a requirement dependency on it.
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz download-cloud-config.sh[2877]: • A unit may be started when needed via activation (socket, path, timer,
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz download-cloud-config.sh[2877]:   D-Bus, udev, scripted systemctl call, ...).
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz download-cloud-config.sh[2877]: • In case of template units, the unit is meant to be enabled with some
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz download-cloud-config.sh[2877]:   instance name specified.
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz systemd-coredump[2881]: Process 2880 (systemd) of user 0 dumped core.

                                                                                                      Stack trace of thread 2880:
                                                                                                      #0  0x00007f7a57e5ea47 kill (libc.so.6 + 0x3ba47)
                                                                                                      #1  0x00005622340c87df n/a (systemd + 0xe57df)
                                                                                                      #2  0x00007f7a57e5e7e0 n/a (libc.so.6 + 0x3b7e0)
                                                                                                      #3  0x0000562234075990 n/a (systemd + 0x92990)
                                                                                                      #4  0x0000562234075e17 n/a (systemd + 0x92e17)
                                                                                                      #5  0x000056223408cd3c n/a (systemd + 0xa9d3c)
                                                                                                      #6  0x00005622340c5f9b n/a (systemd + 0xe2f9b)
                                                                                                      #7  0x000056223401a728 n/a (systemd + 0x37728)
                                                                                                      #8  0x00007f7a57e49e0b __libc_start_main (libc.so.6 + 0x26e0b)
                                                                                                      #9  0x000056223401b59a n/a (systemd + 0x3859a)
Apr 09 15:11:55 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz download-cloud-config.sh[2883]: Failed to enable unit: Connection reset by peer
Apr 09 15:12:21 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz dbus-daemon[392]: [system] Failed to activate service 'org.freedesktop.systemd1': timed out (service_start_timeout=25000ms)
Apr 09 15:12:21 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz kubelet[2852]: I0409 15:12:21.962954    2852 mount_linux.go:170] Cannot run systemd-run, assuming non-systemd OS
Apr 09 15:12:21 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz kubelet[2852]: I0409 15:12:21.963076    2852 server.go:425] Version: v1.15.11
Apr 09 15:12:21 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz kubelet[2852]: I0409 15:12:21.963173    2852 feature_gate.go:216] feature gates: &{map[]}
Apr 09 15:12:21 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz kubelet[2852]: I0409 15:12:21.963288    2852 feature_gate.go:216] feature gates: &{map[]}
Apr 09 15:12:21 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz kubelet[2852]: W0409 15:12:21.963458    2852 plugins.go:118] WARNING: gce built-in cloud provider is now deprecated. The GCE provider is deprecated and wil>
Apr 09 15:12:21 shoot--core--gardenlinux-gcp-worker-i6pqb-z1-86bf99d88b-t6grz kubelet[2852]: I0409 15:12:21.970282    2852 gce.go:868] Using existing Token Source &oauth2.reuseTokenSource{new:google.computeSource{account:"", scopes:[>
```

**Comment by marwinski** [comment]
We have found and resolved / worked around the issue. gdb hinted at the cause. This is the stack trace:

```
(gdb) bt
#0  0x00007ff05706fa47 in kill () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x0000562eb117394f in crash (sig=11) at ../src/core/main.c:212
#2  <signal handler called>
#3  service_exec_command_index (current=0x562eb15f2970, id=_SERVICE_EXEC_COMMAND_INVALID, u=0x562eb15f09a0) at ../src/core/service.c:2577
#4  service_serialize_exec_command (u=u@entry=0x562eb15f09a0, f=f@entry=0x562eb1533a10, command=0x562eb15f2970) at ../src/core/service.c:2605
#5  0x0000562eb1121157 in service_serialize (u=0x562eb15f09a0, f=0x562eb1533a10, fds=0x562eb151b0d0) at ../src/core/service.c:2671
#6  0x0000562eb1138dac in unit_serialize (serialize_jobs=true, fds=0x562eb151b0d0, f=0x562eb1533a10, u=0x562eb15f09a0) at ../src/core/unit.h:626
#7  manager_serialize (m=0x562eb14a6580, f=0x562eb1533a10, fds=0x562eb151b0d0, switching_root=<optimized out>) at ../src/core/manager.c:3246
#8  0x0000562eb116f700 in manager_reload (m=0x562eb14a6580) at ../src/core/manager.c:3533
#9  invoke_main_loop (m=0x562eb14a6580, saved_rlimit_nofile=<optimized out>, saved_rlimit_memlock=<optimized out>, ret_reexecute=<optimized out>, ret_retval=<optimized out>, ret_shutdown_verb=<optimized out>, ret_fds=<optimized out>,
    ret_switch_root_dir=<optimized out>, ret_switch_root_init=<optimized out>, ret_error_message=<optimized out>) at ../src/core/main.c:1764
#10 0x0000562eb10c33f3 in main (argc=<optimized out>, argv=<optimized out>) at ../src/core/main.c:2700
```

This is in line with our observation that the crash happend during or after a daemon reload. This is the "offending" unit:

```
(gdb) p *((Unit*)(0x562eb15f09a0))
$1 = {manager = 0x562eb14a6580, type = UNIT_SERVICE, load_state = UNIT_LOADED, merged_into = 0x0,
  id = 0x562eb15fb200 "systemd-hostnamed.service", instance = 0x0, names = 0x562eb1571c58, dependencies = {0x562eb1519070,
    0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x562eb14e7f58, 0x0, 0x562eb15717f8, 0x562eb1570330, 0x0, 0x0, 0x0, 0x0,
    0x0, 0x0, 0x562eb151f5f0, 0x0}, requires_mounts_for = 0x562eb1571718, description = 0x562eb1614f80 "Hostname Service",
  documentation = 0x562eb15f2620, fragment_path = 0x562eb15339d0 "/lib/systemd/system/systemd-hostnamed.service",
  source_path = 0x0, dropin_paths = 0x562eb1569b70, fragment_mtime = 1586512515000000, source_mtime = 0,
  dropin_mtime = 1587045241569428, transient_file = 0x0, job = 0x562eb15f1700, nop_job = 0x0,
  match_bus_slot = 0x562eb15f17b0, get_name_owner_slot = 0x0, bus_track = 0x0, deserialized_refs = 0x0,
  job_timeout = 18446744073709551615, job_running_timeout = 18446744073709551615, job_running_timeout_set = false,
  job_timeout_action = EMERGENCY_ACTION_NONE, job_timeout_reboot_arg = 0x0, refs_by_target = 0x0, conditions = 0x0,
  asserts = 0x0, condition_timestamp = {realtime = 1587045240777669, monotonic = 47983427}, assert_timestamp = {
    realtime = 1587045240777669, monotonic = 47983428}, state_change_timestamp = {realtime = 1587045241135610,
    monotonic = 48341369}, inactive_exit_timestamp = {realtime = 1587045240779973, monotonic = 47985732},
  active_enter_timestamp = {realtime = 0, monotonic = 0}, active_exit_timestamp = {realtime = 0, monotonic = 0},
  inactive_enter_timestamp = {realtime = 0, monotonic = 0}, slice = {source = 0x562eb15f09a0, target = 0x562eb1595d70,
    refs_by_target_next = 0x562eb15c6888, refs_by_target_prev = 0x562eb16392c8}, units_by_type_next = 0x562eb15c4360,
  units_by_type_prev = 0x562eb1635940, load_queue_next = 0x0, load_queue_prev = 0x0, dbus_queue_next = 0x0,
  dbus_queue_prev = 0x0, cleanup_queue_next = 0x0, cleanup_queue_prev = 0x0, gc_queue_next = 0x0, gc_queue_prev = 0x0,
  cgroup_realize_queue_next = 0x0, cgroup_realize_queue_prev = 0x0, cgroup_empty_queue_next = 0x0,
  cgroup_empty_queue_prev = 0x0, cgroup_oom_queue_next = 0x0, cgroup_oom_queue_prev = 0x0, target_deps_queue_next = 0x0,
  target_deps_queue_prev = 0x0, stop_when_unneeded_queue_next = 0x0, stop_when_unneeded_queue_prev = 0x0,
  pids = 0x562eb1573200, sigchldgen = 0, notifygen = 0, gc_marker = 5678, load_error = 0, start_ratelimit = {
    interval = 10000000, burst = 5, num = 0, begin = 0}, start_limit_action = EMERGENCY_ACTION_NONE,
  success_action = EMERGENCY_ACTION_NONE, failure_action = EMERGENCY_ACTION_NONE, success_action_exit_status = -1,
  failure_action_exit_status = -1, reboot_arg = 0x0, auto_stop_ratelimit = {interval = 10000000, burst = 16, num = 0,
    begin = 0}, ref_uid = 4294967295, ref_gid = 4294967295, unit_file_state = _UNIT_FILE_STATE_INVALID,
  unit_file_preset = -1, cpu_usage_base = 0, cpu_usage_last = 18446744073709551615, oom_kill_last = 0,
  io_accounting_base = {0, 0, 0, 0}, io_accounting_last = {18446744073709551615, 18446744073709551615,
    18446744073709551615, 18446744073709551615}, cgroup_path = 0x562eb15f1c20 "/system.slice/systemd-hostnamed.service",
  cgroup_realized_mask = 1011, cgroup_enabled_mask = 0, cgroup_invalidated_mask = 0, cgroup_members_mask = 0,
  cgroup_control_inotify_wd = 462, cgroup_memory_inotify_wd = -1, bpf_device_control_installed = 0x0,
  ip_accounting_ingress_map_fd = -1, ip_accounting_egress_map_fd = -1, ipv4_allow_map_fd = -1, ipv6_allow_map_fd = -1,
  ipv4_deny_map_fd = -1, ipv6_deny_map_fd = -1, ip_bpf_ingress = 0x562eb157c8d0,
  ip_bpf_ingress_installed = 0x562eb157c8d0, ip_bpf_egress = 0x562eb1612330, ip_bpf_egress_installed = 0x562eb1612330,
  ip_bpf_custom_ingress = 0x0, ip_bpf_custom_ingress_installed = 0x0, ip_bpf_custom_egress = 0x0,
  ip_bpf_custom_egress_installed = 0x0, ip_accounting_extra = {0, 0, 0, 0}, rewatch_pids_event_source = 0x0,
  on_failure_job_mode = JOB_REPLACE, collect_mode = COLLECT_INACTIVE, invocation_id = {
    bytes = "{B\200\362\362\071E\264\254\253\027X\345ʚ{", qwords = {12989852415833424507, 8906654299452844972}},
  invocation_id_string = "7b4280f2f23945b4acab1758e5ca9a7b", stop_when_unneeded = false, default_dependencies = true,
  refuse_manual_start = false, refuse_manual_stop = false, allow_isolate = false, ignore_on_isolate = false,
  condition_result = true, assert_result = true, transient = false, perpetual = false, in_load_queue = false,
  in_dbus_queue = false, in_cleanup_queue = false, in_gc_queue = false, in_cgroup_realize_queue = false,
  in_cgroup_empty_queue = false, in_cgroup_oom_queue = false, in_target_deps_queue = false,
  in_stop_when_unneeded_queue = false, sent_dbus_new_signal = true, in_audit = false, on_console = false,
  cgroup_realized = true, cgroup_members_mask_valid = true, reset_accounting = false, start_limit_hit = false,
  coldplugged = true, bus_track_add = false, exported_invocation_id = true, exported_log_level_max = false,
  exported_log_extra_fields = false, exported_log_ratelimit_interval = false, exported_log_ratelimit_burst = false,
  warned_clamping_cpu_quota_period = false, last_section_private = -1}
```

We introduced the unit to set the hostname in the  ```/etc/hostname``` file (which was not needed). We removed the unit and the crash went away. 

We don't understand why this sometimes causes a systemd crash. We consider this a systemd bug but currently have no resources for further investigation to file a systemd issue or propose a fix.
