### ISSUE TITLE
Building iso-Image fails because of missing garden-chroot

### ISSUE THREAD

**Issue by dnan0s** [gardenlinux/gardenlinux#1722]
**What happened:**

When building with activated `_iso`-Feature the build fails. What i've seen from the builder so far, the `bin`-Folder is not mounted into the build-container anymore, and while running the script `feature/_iso/image` the command `garden-chroot` is not found anymore.

**Debug Logs:**

```
[.build/metal_iso-amd64-today-local.tar 2023-08-03 13:30:18] 22d6802a3233c7dd0740ff0f6b7e05b716c68787a3b86031c7a2a744546ff0f2  .build/metal_iso-amd64-today-local.tar
completed in 55 seconds

building release image metal_iso-amd64-today
completed in 1 seconds

building manifest image metal_iso-amd64-today
completed in 1 seconds

Traceback (most recent call last):
  File "/builder/./parse_features", line 198, in <module>
    main()
  File "/builder/./parse_features", line 40, in main
    assert search, f"not a valid cname {args.cname}"
AssertionError: not a valid cname features/_iso/image
Traceback (most recent call last):
  File "/builder/./parse_features", line 198, in <module>
    main()
  File "/builder/./parse_features", line 40, in main
    assert search, f"not a valid cname {args.cname}"
AssertionError: not a valid cname features/_iso/image
building raw image metal_iso-amd64-today
[.build/metal_iso-amd64-today-local.raw 2023-08-03 13:30:20] ./features/_iso/image: line 10: garden-chroot: command not found
completed in 0 seconds

make: *** [Makefile:84: .build/metal_iso-amd64-today-local.raw] Error 127
```

**How to reproduce it**:
- i've been testing it with plain `./build metal_iso`

**Environment:**

| Name | Value |
| ------------------- | ----- |
| Garden Linux Branch | main |
| Container runtime: | podman | 
| Host OS: | tested on two machines: Debian 12 VM and Fedora (quay.io podman Container) |

**Comment by gehoern** [comment]
i think this is because of the new builder. but we still need to support iso's
