### ISSUE TITLE
docker leaves an orphan container that is causing infinite kubelet panics on kubelet restart

### ISSUE THREAD

**Issue by ialidzhikov** [gardenlinux/gardenlinux#280]
/kind bug

**What happened**:

With Garden Linux 184.0.0 docker leaves an orphan node-exported container that is causing kubelet panics on kubelet restart.

**What you expected to happen**:

No orphan containers and kubelet to be able to start successfully after restart.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a Shoot cluster with Kubernetes v1.21.x and Garden Linux 184.0.0

2. Make sure that orphan node-exported containers exist after successful Shoot creation

The node-exported Pods are with a single restart:

```
$ k -n kube-system get po -l component=node-exporter
NAME                  READY   STATUS    RESTARTS   AGE
node-exporter-qc6t5   1/1     Running   1          31m
node-exporter-x7nxk   1/1     Running   1          30m
```

The Pod statuses:

```
$ k -n kube-system get po node-exporter-qc6t5 -o jsonpath='{.status.containerStatuses}' | jq
[
  {
    "containerID": "docker://17b77b024374d51156cce47e2e9c6925faadcb658124dcd426fb0b2214afc0d6",
    "image": "sha256:92c0bc9bfa155b6fb88ace153a6050726a29a3d1f43594b13017d8a936809197",
    "imageID": "docker-pullable://eu.gcr.io/sap-se-gcr-k8s-public/quay_io/prometheus/node-exporter@sha256:eeed365560149e3d390eafd6ce8154bcde401aed06f18e6ceedc01cbeadf0bc3",
    "lastState": {
      "terminated": {
        "containerID": "docker://613305690b544984e9509a6d9d71e022ca3ad90c5c0275deccbee8a0c9b5d98d",
        "exitCode": 128,
        "finishedAt": "2021-07-08T06:46:57Z",
        "message": "No such container: 6d85eb5410fffafc8e6b97ddc5b9afed8237ac68fe6239fba990eee5cf294124",
        "reason": "ContainerCannotRun",
        "startedAt": "2021-07-08T06:46:57Z"
      }
    },
    "name": "node-exporter",
    "ready": true,
    "restartCount": 1,
    "started": true,
    "state": {
      "running": {
        "startedAt": "2021-07-08T06:47:05Z"
      }
    }
  }
]
```

```
$ k -n kube-system get po node-exporter-x7nxk -o jsonpath='{.status.containerStatuses}' | jq
[
  {
    "containerID": "docker://a5f35a5fd0e5e1f2d4856973a3bda12843aba4cb97baf6aeda49e4847c2585e4",
    "image": "sha256:92c0bc9bfa155b6fb88ace153a6050726a29a3d1f43594b13017d8a936809197",
    "imageID": "docker-pullable://eu.gcr.io/sap-se-gcr-k8s-public/quay_io/prometheus/node-exporter@sha256:eeed365560149e3d390eafd6ce8154bcde401aed06f18e6ceedc01cbeadf0bc3",
    "lastState": {
      "terminated": {
        "containerID": "docker://b8ae858d76a1c6e554523d44f13687a04d23833a9c03aae1fedc02f2a025e0ad",
        "exitCode": 128,
        "finishedAt": "2021-07-08T06:48:13Z",
        "message": "No such container: bd19547090fead78a9e72be943030554b176715c3371565eeeaec3eed94fe5ea",
        "reason": "ContainerCannotRun",
        "startedAt": "2021-07-08T06:48:13Z"
      }
    },
    "name": "node-exporter",
    "ready": true,
    "restartCount": 1,
    "started": true,
    "state": {
      "running": {
        "startedAt": "2021-07-08T06:48:20Z"
      }
    }
  }
]
```

You can see that the first container failed with reasons `No such container: <id>`.

3. Make sure that orphan node-exporter docker containers exists on the Node

```
# docker ps -a | grep node_exporter
a5f35a5fd0e5        92c0bc9bfa15                                                                             "/bin/node_exporter …"   40 minutes ago       Up 40 minutes                                   k8s_node-exporter_node-exporter-x7nxk_kube-system_1cf99e57-b1d8-478e-9678-9ff0d1c3dbf3_1
b8ae858d76a1        quay.io/prometheus/node-exporter                                                         "/bin/node_exporter …"   40 minutes ago       Created                                         k8s_node-exporter_node-exporter-x7nxk_kube-system_1cf99e57-b1d8-478e-9678-9ff0d1c3dbf3_0
```

You can see that container `b8ae858d76a1` is orphan. It is in Created `state`.

3. Restart kubelet on the Nodes (generally kubelet can be restarted because of feature flag change; it can be restarted by the kubelet-monitor service, etc.)

ssh to the Node and restart kubelet:

```
# systemctl restart kubelet
```

4. Make sure that kubelet panic infinitely and cannot recover after the restart

```
$ k get no ip-10-250-11-209.eu-west-1.compute.internal
NAME                                          STATUS     ROLES    AGE   VERSION
ip-10-250-11-209.eu-west-1.compute.internal   NotReady   <none>   43m   v1.21.2
```

```
Events:
  Type     Reason                   Age                From             Message
  ----     ------                   ----               ----             -------
  Normal   Starting                 46m                kubelet          Starting kubelet.
  Normal   NodeHasSufficientMemory  46m                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    46m                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     46m                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientPID
  Normal   NodeAllocatableEnforced  46m                kubelet          Updated Node Allocatable limit across pods
  Normal   Starting                 46m                kubelet          Starting kubelet.
  Normal   NodeHasSufficientMemory  46m                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    46m                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     46m                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientPID
  Normal   NodeAllocatableEnforced  45m                kubelet          Updated Node Allocatable limit across pods
  Normal   NodeReady                45m                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeReady
  Normal   Starting                 45m                kube-proxy       Starting kube-proxy.
  Warning  DockerStart              43m (x2 over 43m)  systemd-monitor  Starting Docker Application Container Engine...
  Normal   Starting                 2m35s              kubelet          Starting kubelet.
  Normal   NodeHasSufficientMemory  2m35s              kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    2m35s              kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     2m35s              kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientPID
  Normal   NodeNotReady             2m34s              kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeNotReady
  Normal   Starting                 2m27s              kubelet          Starting kubelet.
  Normal   NodeHasSufficientMemory  2m27s              kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    2m27s              kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     2m27s              kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientPID
  Normal   Starting                 2m20s              kubelet          Starting kubelet.
  Normal   NodeHasSufficientMemory  2m20s              kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientMemory
  Normal   NodeHasSufficientPID     2m20s              kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientPID
  Normal   NodeHasNoDiskPressure    2m20s              kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasNoDiskPressure
  Normal   Starting                 2m13s              kubelet          Starting kubelet.
  Normal   NodeHasSufficientMemory  2m13s              kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    2m13s              kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     2m13s              kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientPID
  Normal   Starting                 2m6s               kubelet          Starting kubelet.
  Normal   NodeHasSufficientMemory  2m5s               kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    2m5s               kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     2m5s               kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientPID
  Normal   Starting                 118s               kubelet          Starting kubelet.
  Normal   NodeHasSufficientMemory  118s               kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    118s               kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     118s               kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientPID
  Normal   Starting                 111s               kubelet          Starting kubelet.
  Normal   NodeHasSufficientMemory  111s               kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    111s               kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     111s               kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientPID
  Normal   Starting                 104s               kubelet          Starting kubelet.
  Normal   NodeHasSufficientMemory  103s               kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    103s               kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     103s               kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientPID
  Normal   Starting                 96s                kubelet          Starting kubelet.
  Normal   NodeHasSufficientMemory  96s                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    96s                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     96s                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientPID
  Normal   Starting                 89s                kubelet          Starting kubelet.
  Normal   NodeHasSufficientMemory  88s                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    88s                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     88s                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientPID
  Normal   Starting                 81s                kubelet          Starting kubelet.
  Normal   NodeHasSufficientMemory  81s                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    81s                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     81s                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientPID
  Normal   Starting                 74s                kubelet          Starting kubelet.
  Normal   NodeHasSufficientMemory  74s                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    74s                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     74s                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientPID
  Normal   NodeHasSufficientPID     66s                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientPID
  Normal   NodeHasSufficientMemory  66s                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    66s                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasNoDiskPressure
  Normal   Starting                 66s                kubelet          Starting kubelet.
  Normal   Starting                 59s                kubelet          Starting kubelet.
  Normal   NodeHasSufficientMemory  59s                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    59s                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     59s                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientPID
  Normal   Starting                 52s                kubelet          Starting kubelet.
  Normal   NodeHasSufficientMemory  52s                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    52s                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     52s                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientPID
  Normal   Starting                 45s                kubelet          Starting kubelet.
  Normal   NodeHasSufficientMemory  44s                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    44s                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     44s                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientPID
  Normal   Starting                 37s                kubelet          Starting kubelet.
  Normal   NodeHasSufficientMemory  37s                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    37s                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     37s                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientPID
  Normal   Starting                 30s                kubelet          Starting kubelet.
  Normal   NodeHasSufficientMemory  29s                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    29s                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     29s                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientPID
  Normal   NodeHasSufficientMemory  22s                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    22s                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     22s                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientPID
  Normal   Starting                 22s                kubelet          Starting kubelet.
  Normal   NodeHasSufficientMemory  14s                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientMemory
  Normal   Starting                 14s                kubelet          Starting kubelet.
  Normal   NodeHasNoDiskPressure    14s                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     14s                kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientPID
  Normal   Starting                 7s                 kubelet          Starting kubelet.
  Normal   NodeHasSufficientMemory  7s                 kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    7s                 kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     7s                 kubelet          Node ip-10-250-11-209.eu-west-1.compute.internal status is now: NodeHasSufficientPID
```

The kubelet will never recover from this issue and the Node will be replaced after time.

The corresponding panic looks like:

```
Jun 23 08:35:21 ip-10-250-9-79.eu-central-1.compute.internal kubelet[2027990]: F0623 08:35:21.378741 2027990 kubelet.go:1372] Failed to start ContainerManager failed to build map of initial containers from runtime: no PodsandBox found with Id '<id of failed node-exported container>'
Jun 23 08:35:21 ip-10-250-9-79.eu-central-1.compute.internal kubelet[2027990]: goroutine 316 [running]:
Jun 23 08:35:21 ip-10-250-9-79.eu-central-1.compute.internal kubelet[2027990]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc000010001, 0xc0000fe280, 0xe7, 0x267)
Jun 23 08:35:21 ip-10-250-9-79.eu-central-1.compute.internal kubelet[2027990]:         /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
Jun 23 08:35:21 ip-10-250-9-79.eu-central-1.compute.internal kubelet[2027990]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x70e3580, 0xc000000003, 0x0, 0x0, 0xc0009e9260, 0x6f4f612, 0xa, 0x55c, 0x0)
Jun 23 08:35:21 ip-10-250-9-79.eu-central-1.compute.internal kubelet[2027990]:         /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:975 +0x19b
Jun 23 08:35:21 ip-10-250-9-79.eu-central-1.compute.internal kubelet[2027990]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printf(0x70e3580, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x4944a35, 0x23, 0xc001497150, 0x1, ...)
Jun 23 08:35:21 ip-10-250-9-79.eu-central-1.compute.internal kubelet[2027990]:         /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:750 +0x191
Jun 23 08:35:21 ip-10-250-9-79.eu-central-1.compute.internal kubelet[2027990]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.Fatalf(...)
Jun 23 08:35:21 ip-10-250-9-79.eu-central-1.compute.internal kubelet[2027990]:         /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1502
Jun 23 08:35:21 ip-10-250-9-79.eu-central-1.compute.internal kubelet[2027990]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).initializeRuntimeDependentModules(0xc0007ee000)
Jun 23 08:35:21 ip-10-250-9-79.eu-central-1.compute.internal kubelet[2027990]:         /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1372 +0x446
Jun 23 08:35:21 ip-10-250-9-79.eu-central-1.compute.internal kubelet[2027990]: sync.(*Once).doSlow(0xc0007ee850, 0xc000f63de8)
Jun 23 08:35:21 ip-10-250-9-79.eu-central-1.compute.internal kubelet[2027990]:         /usr/local/go/src/sync/once.go:66 +0xec
Jun 23 08:35:21 ip-10-250-9-79.eu-central-1.compute.internal kubelet[2027990]: sync.(*Once).Do(...)
Jun 23 08:35:21 ip-10-250-9-79.eu-central-1.compute.internal kubelet[2027990]:         /usr/local/go/src/sync/once.go:57
Jun 23 08:35:21 ip-10-250-9-79.eu-central-1.compute.internal kubelet[2027990]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).updateRuntimeUp(0xc0007ee000)
Jun 23 08:35:21 ip-10-250-9-79.eu-central-1.compute.internal kubelet[2027990]:         /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:2204 +0x659
Jun 23 08:35:21 ip-10-250-9-79.eu-central-1.compute.internal kubelet[2027990]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000c99e70)
Jun 23 08:35:21 ip-10-250-9-79.eu-central-1.compute.internal kubelet[2027990]:         /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
Jun 23 08:35:21 ip-10-250-9-79.eu-central-1.compute.internal kubelet[2027990]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000c99e70, 0x4f22d60, 0xc000b753e0, 0x1, 0xc00009e0c0)
Jun 23 08:35:21 ip-10-250-9-79.eu-central-1.compute.internal kubelet[2027990]:         /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
Jun 23 08:35:21 ip-10-250-9-79.eu-central-1.compute.internal kubelet[2027990]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000c99e70, 0x12a05f200, 0x0, 0x4a87801, 0xc00009e0c0)
Jun 23 08:35:21 ip-10-250-9-79.eu-central-1.compute.internal kubelet[2027990]:         /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
Jun 23 08:35:21 ip-10-250-9-79.eu-central-1.compute.internal kubelet[2027990]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc000c99e70, 0x12a05f200, 0xc00009e0c0)
Jun 23 08:35:21 ip-10-250-9-79.eu-central-1.compute.internal kubelet[2027990]:         /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
```

**Anything else we need to know**:

I did experiments to check with which versions of Garden Linux the issue is reproducible.

I am able to reproduce the issue with:
- Garden Linux 184.0.0 + docker

I am NOT able to reproduce the issue with:
- Garden Linux 184.0.0 + containerd
- Garden Linux 318.8.0 + docker

Hence, I suspect that this is an issue with the docker version of Garden Linux 184.0.0.

**Environment**:
Kubernetes version - v1.21.2
Garden Linux version - 184.0.0

**Comment by marwinski** [comment]
Here is some initial investigation:

- to the best of my knowledge we only see this issue with Kubernetes 1.21.x which is still in preview. I have checked a 1.19 cluster which does not have this issue. I assume Kubernetes 1.20 will also work fine.
- Kubelet 1.21.2 is built against Docker v20.10.2 where Kubelet 1.20.8 is built against Docker v17.12.0
- Garden Linux 184.0 comes with Docker 19.03.13 where Garden Linux comes with Docker 20.10.5+dfsg1

I'd suspect the Docker version update in the Kubelet does contribute to the issue (e.g. a newer Docker client talking to an older Docker implementation).

**Comment by ialidzhikov** [comment]
>  I assume Kubernetes 1.20 will also work fine.

Nope, this issue affects v1.20.x as well. My initial investigations were even on v1.20.x. I will update the issue that v1.20.x is also an affected version.

**Comment by marwinski** [comment]
No a solution but possibly a viable workaround: Restarting docker removes the stale container, so instead of just restarting the kubelet, docker should be restarted beforehand. 

Some further analysis. On starting the "broken container" the following error message appears in the log. This is true for both, through the kubelet and through `docker start`:

```
Jul 09 07:09:50 shoot--d040949--no-panic-worker-iejcm-z1-765d6-2hc59 dockerd[2977]: time="2021-07-09T07:09:50.768218407Z" level=error msg="75a524941816804030d48a97f761cdf38c5418f9e2a59e3666cd1945293e494a cleanup: failed to delete container from containerd: no such container"
```

I restarted docker with log level debug. Upon restart the broken container was removed (checked though `docker ps -a`). This appears in the log:

```
Jul 09 07:52:43 shoot--d040949--no-panic-worker-iejcm-z1-765d6-2hc59 dockerd[132445]: time="2021-07-09T07:52:43.227596005Z" level=debug msg="Calling DELETE /v1.40/containers/75a524941816804030d48a97f761cdf38c5418f9e2a59e3666cd1945293e494a?force=1&v=1"
```

**Comment by marwinski** [comment]
PS: This is the docker issue that describes the problem: https://github.com/docker/for-linux/issues/1148

Unfortunately there is no solution but it mentions the same workaround as I did above.

**Comment by marwinski** [comment]
@MrBatschner: The OS extension is probably the only component that restarts the kubelet!?

It appears that docker can be restarted without stopping all the containers (see https://docs.docker.com/config/containers/live-restore/#enable-live-restore). It also appears the default setting.

**Comment by kiocosta** [comment]
any solution for this?

**Comment by sramapu** [comment]
close stale issue
