### ISSUE TITLE
Can't log on with admin on Alicloud

### ISSUE THREAD

**Issue by jia-jerry** [gardenlinux/gardenlinux#52]
**What happened**:
Can't log on with admin on Alicloud. Cloud-init failed.
**What you expected to happen**:
**How to reproduce it (as minimally and precisely as possible)**:
Latest master branch.
**Anything else we need to know**:
I used to build an image with alicloud branch. It worked. Below is the comparison of the cloud-init log.
Success one:
```
2020-05-18 17:57:35,896 - handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: no cache found
2020-05-18 17:57:35,896 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2020-05-18 17:57:35,897 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.debian.Distro'>
2020-05-18 17:57:35,897 - __init__.py[DEBUG]: Looking for data source in: ['AliYun', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM', 'NETWORK']
2020-05-18 17:57:35,899 - __init__.py[DEBUG]: Searching for network data source in: ['DataSourceAliYun', 'DataSourceNone']
2020-05-18 17:57:35,900 - handlers.py[DEBUG]: start: init-network/search-AliYun: searching for network data from DataSourceAliYun
2020-05-18 17:57:35,900 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceAliYun.DataSourceAliYun'>
2020-05-18 17:57:35,900 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
2020-05-18 17:57:35,900 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2020-05-18 17:57:35,905 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2020-05-18 17:57:35,907 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2020-05-18 17:57:35,908 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2020-05-18 17:57:35,908 - util.py[DEBUG]: Read 153 bytes from /proc/1/environ
2020-05-18 17:57:35,908 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2020-05-18 17:57:35,908 - util.py[DEBUG]: Read 1027 bytes from /proc/self/status
2020-05-18 17:57:35,908 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_name
2020-05-18 17:57:35,908 - util.py[DEBUG]: Reading from /sys/class/dmi/id/product_name (quiet=False)
```

Failed one:
```
2020-05-18 06:36:44,286 - handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: no cache found
2020-05-18 06:36:44,286 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2020-05-18 06:36:44,288 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.debian.Distro'>
2020-05-18 06:36:44,288 - __init__.py[DEBUG]: Looking for data source in: ['AliYun', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM', 'NETWORK']
2020-05-18 06:36:44,290 - __init__.py[DEBUG]: Searching for network data source in: ['DataSourceAliYun', 'DataSourceNone']
2020-05-18 06:36:44,290 - handlers.py[DEBUG]: start: init-network/search-AliYun: searching for network data from DataSourceAliYun
2020-05-18 06:36:44,290 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceAliYun.DataSourceAliYun'>
2020-05-18 06:36:44,290 - handlers.py[DEBUG]: finish: init-network/search-AliYun: FAIL: no network data found from DataSourceAliYun
2020-05-18 06:36:44,290 - util.py[WARNING]: Getting data from <class 'cloudinit.sources.DataSourceAliYun.DataSourceAliYun'> failed
2020-05-18 06:36:44,294 - util.py[DEBUG]: Getting data from <class 'cloudinit.sources.DataSourceAliYun.DataSourceAliYun'> failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/sources/__init__.py", line 756, in find_source
    s = cls(sys_cfg, distro, paths)
  File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceEc2.py", line 78, in __init__
    super(DataSourceEc2, self).__init__(sys_cfg, distro, paths)
  File "/usr/lib/python3/dist-packages/cloudinit/sources/__init__.py", line 208, in __init__
    self.ds_cfg = util.get_cfg_by_path(
  File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 733, in get_cfg_by_path
    cur = cur[tok]
TypeError: string indices must be integers
2020-05-18 06:36:44,295 - handlers.py[DEBUG]: start: init-network/search-None: searching for network data from DataSourceNone
2020-05-18 06:36:44,295 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceNone.DataSourceNone'>
2020-05-18 06:36:44,295 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
```
**Environment**:
Alicloud

**Comment by marwinski** [comment]
Fixed with https://github.com/gardenlinux/gardenlinux/commit/2a20bc22fa7cb646ee2f99892713ab70ff114946
